In [29]:
import pandas as pd
import os
from pathlib import Path
from dotenv import load_dotenv
%matplotlib inline

In [2]:
superbowl_df = Path ("../Project-1_Team-2/superbowl_data.csv")

superbowl = pd.read_csv(
    superbowl_df, index_col="SB")
superbowl.head()

,Date,Winner,Winner Pts,Loser,Loser Pts,MVP,Stadium,City,State
SB,,,,,,,,,
LV (55),Feb 7 2020,Tampa Bay Buccaneers,31,Kansas City Chiefs,9,Tom Brady,Raymond James Stadium,Tampa,Florida
LIV (54),Feb 2 2020,Kansas City Chiefs,31,San Francisco 49ers,20,Patrick Mahomes,Hard Rock Stadium,Miami Gardens,Florida
LIII (53),Feb 3 2019,New England Patriots,13,Los Angeles Rams,3,Julian Edelman,Mercedes-Benz Stadium,Atlanta,Georgia
LII (52),Feb 4 2018,Philadelphia Eagles,41,New England Patriots,33,Nick Foles,U.S. Bank Stadium,Minneapolis,Minnesota
LI (51),Feb 5 2017,New England Patriots,34,Atlanta Falcons,28,Tom Brady,NRG Stadium,Houston,Texas

In [10]:
raw_data = pd.DataFrame([])
years_start = 1996
years_end = 2022
for year in range(years_start,years_end):
        url = f'https://www.pro-football-reference.com/years/{year}/preseason_odds.htm'
        df = pd.read_html(url)[0]
        df['year'] = year
        raw_data = raw_data.append(df, ignore_index=True, sort=False)
raw_data

                           Tm  Super Bowl Odds  W/L O-U        Record  year
0           Arizona Cardinals            12000      5.5    7-9 (over)  1996
1             Atlanta Falcons             4000      8.0  3-13 (under)  1996
2            Baltimore Ravens             3000      7.5  4-12 (under)  1996
3               Buffalo Bills             1500      8.5   10-6 (over)  1996
4           Carolina Panthers             8000      5.5   12-4 (over)  1996
..                        ...              ...      ...           ...   ...
818       San Francisco 49ers             1400     10.5          10-7  2021
819          Seattle Seahawks             2500      9.5          7-10  2021
820      Tampa Bay Buccaneers              700     12.0          13-4  2021
821          Tennessee Titans             2000      9.5          12-5  2021
822  Washington Football Team             4000      8.5          7-10  2021

[823 rows x 5 columns]

In [31]:
load_dotenv()

True

In [32]:
sportsdata_io = os.getenv("sports_io")

In [36]:
mapbox = os.getenv("mapbox_api_key")